#!/bin/bash

unset AWS_ACCESS_KEY_ID
unset AWS_SECRET_ACCESS_KEY
unset AWS_SESSION_TOKEN

if [[ -z $1 ]]; then
  echo Role ARN required
  exit 1
fi

export aws_assume_creds=$(aws sts assume-role --role-arn $1 --role-session-name sg-audit)
export AWS_ACCESS_KEY_ID=$(echo $aws_assume_creds | jq -r ".Credentials.AccessKeyId" | tr -d "\n")
export AWS_SECRET_ACCESS_KEY=$(echo $aws_assume_creds | jq -r ".Credentials.SecretAccessKey" | tr -d "\n")
export AWS_SESSION_TOKEN=$(echo $aws_assume_creds | jq -r ".Credentials.SessionToken" | tr -d "\n")
