#!/bin/bash

trap ctrl_c INT
ctrl_c() {
	exit 1
}

DATA_DIR=${DATA_DIR:-"data"}
ROLES=($(./listroles))
REGIONS=($(./listregions))

for r in ${ROLES[@]}; do
	echo checking role $r > /dev/stderr
	source ./assumerole "$r"
	source ./getaccountalias
	export ROLE_ARN=$r
	for n in ${REGIONS[@]}; do
		echo checking region $n > /dev/stderr
		export AWS_REGION=$n
		./listunattached &
		./listopensgs &
		wait
	done
done

./listopenunattached

./s3upload
